package panoptes.api;

import org.springframework.stereotype.Service;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestClient;

import panoptes.dto.DetailedResult;
import panoptes.dto.JsonApiResponseDto;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The dedicated API client for communicating with the external <a href="https://ideenatlas.eu">Ideenatlas</a> search engine.
 * <p>
 * The Ideenatlas is a semantic "idea curation engine" that maps millions of scientific documents 
 * into a vector space. Instead of relying on keyword matching or citation graphs (which inherently 
 * favor already popular papers), it uses cosine similarity to find conceptually related research.
 * Using an inhouse developed cluster RAG, relevant papers from all across the knowledge space
 * are retrieved.
 * This client sends dense, abstract-style vector queries (generated by Panoptes' planning agents) 
 * to the API to discover literature.
 * </p>
 * <p>
 * To maximize the potential for academic serendipity, this client aggregates results from all three 
 * conceptual tiers provided by the API: direct matches, neighboring topic clusters, and distant 
 * "serendipitous" connections (structurally analogous disciplines). It inherently deduplicates papers 
 * based on their ID and handles HTTP rate-limiting through exponential backoff.
 * </p>
 */
@Service
public class IdeenatlasApiClient {

    private final RestClient restClient;

    public IdeenatlasApiClient() {
        this.restClient = RestClient.builder()
                .baseUrl("https://ideenatlas.eu")
                .build();
    }

    public List<DetailedResult> search(String query) {
        if (query == null || query.isBlank()) {
            return List.of();
        }

        Map<String, String> body = Map.of("query", query);
        int maxRetries = 8;

        for (int i = 0; i < maxRetries; i++) {
            try {
                JsonApiResponseDto response = restClient.post()
                        .uri("/api/search")
                        .body(body)
                        .retrieve()
                        .body(JsonApiResponseDto.class);

                if (response == null) {
                    return List.of();
                }

                // Map to deduplicate results based on their paper-ID
                Map<String, DetailedResult> allPapers = new LinkedHashMap<>();

                // 1. add direct matches
                if (response.detailedSimilarResults() != null) {
                    response.detailedSimilarResults().forEach(paper -> allPapers.put(paper.id(), paper));
                }

                // 2. add papers from similar clusters
                if (response.similarTopicFields() != null) {
                    response.similarTopicFields().forEach(cluster -> {
                        if (cluster.results() != null) {
                            cluster.results().forEach(paper -> allPapers.put(paper.id(), paper));
                        }
                    });
                }

                // 3. add papers from serendipitous clusters
                if (response.serendipitousConnections() != null) {
                    response.serendipitousConnections().forEach(cluster -> {
                        if (cluster.results() != null) {
                            cluster.results().forEach(paper -> allPapers.put(paper.id(), paper));
                        }
                    });
                }

                return new ArrayList<>(allPapers.values());

            } catch (HttpClientErrorException.TooManyRequests e) {
                System.out.println("Rate limit hit for query. Waiting " + (i + 1) + " seconds...");
                try {
                    Thread.sleep(1000L * (i + 1));
                } catch (InterruptedException ie) {
                    Thread.currentThread().interrupt();
                }
            } catch (Exception e) {
                System.err.println("API Error on ideenatlas.eu: " + e.getMessage());
                break;
            }
        }
        return List.of();
    }
}