package panoptes.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A Data Transfer Object (DTO) representing a single step in a research plan.
 * <p>
 * This record is generated by planning agents to break down complex core ideas into 
 * executable sub-tasks. It contains:
 * <ul>
 *   <li><b>question:</b> A human-readable research question (in the user's requested language) 
 *       to guide the LLM investigator. This is also streamed to the frontend UI.</li>
 *   <li><b>vectorQuery:</b> A dense, abstract-style statement (strictly in English) optimized 
 *       for semantic vector search against the ideenatlas.eu API.</li>
 * </ul>
 * </p>
 * <p>
 * <b>Note / Future Work:</b> Currently, the "plan" acts primarily as a collection of targeted 
 * research questions. In future iterations, this structure has the potential to evolve into 
 * complex, multi-layered execution graphs (e.g., conditional searching or sequential tool usage).
 * </p>
 */
public record PlanStep(
        @JsonProperty("question") String question, 
        @JsonProperty("vector_query") String vectorQuery
) {}