package panoptes.service.orchestrator;

import java.util.List;
import java.util.Objects;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.stream.Collectors;

import org.slf4j.MDC;
import org.springframework.stereotype.Service;

import panoptes.agent.AdversarialInvestigatorAgent;
import panoptes.agent.InvestigatorAgent;
import panoptes.agent.RankingAgent;
import panoptes.api.IdeenatlasApiClient;
import panoptes.dto.DetailedResult;
import panoptes.dto.PlanStep;
import panoptes.dto.ResearchContext;
import panoptes.dto.ValidatedResult;
import panoptes.service.PaperValidationService;
import panoptes.util.CitationUtil;
import panoptes.web.SseService;

/**
 * The orchestration layer responsible for executing massively parallel semantic searches.
 * <p>
 * This service takes the search plans generated by the planning agents and executes them 
 * concurrently using Java Virtual Threads. It abstracts away the heavy lifting of:
 * <ul>
 *   <li>Sending vector queries to the external Ideenatlas API.</li>
 *   <li>Piping the retrieved results through the {@link panoptes.service.PaperValidationService} for OpenAlex verification.</li>
 *   <li>Triggering the {@link panoptes.agent.RankingAgent} to filter out irrelevant noise.</li>
 *   <li>Deploying the {@link panoptes.agent.InvestigatorAgent} to extract hard facts from the validated papers.</li>
 * </ul>
 * </p>
 */
@Service
public class InvestigationOrchestrator {
    
    // Start all tasks IMMEDIATELY and entirely in parallel
    private final ExecutorService ioExecutor = Executors.newVirtualThreadPerTaskExecutor();
    
    private final IdeenatlasApiClient apiClient;
    private final PaperValidationService validationService;
    private final RankingAgent rankingAgent;
    private final InvestigatorAgent investigatorAgent;
    private final AdversarialInvestigatorAgent adversarialAgent;
    private final SseService sseService;

    public InvestigationOrchestrator(IdeenatlasApiClient apiClient, PaperValidationService validationService,
                                     RankingAgent rankingAgent, InvestigatorAgent investigatorAgent,
                                     AdversarialInvestigatorAgent adversarialAgent, SseService sseService) {
        this.apiClient = apiClient;
        this.validationService = validationService;
        this.rankingAgent = rankingAgent;
        this.investigatorAgent = investigatorAgent;
        this.adversarialAgent = adversarialAgent;
        this.sseService = sseService;
    }

    public List<String> executeStandardSearch(ResearchContext context, List<PlanStep> steps) {
        List<CompletableFuture<String>> futures = steps.stream().map((PlanStep step) -> 
            CompletableFuture.supplyAsync(() -> {
                MDC.put("jobId", context.getJobId()); // Set MDC per thread
                try {
                    sseService.sendUpdate(context.getJobId(), "Investigating: " + step.question());
                    
                    List<ValidatedResult> topResults = fetchAndValidate(context, step, 75, 30);
                    
                    if (!topResults.isEmpty()) {
                        String contextAwareQuestion = "Context: " + context.getRawInput() + "\nSpecific sub-question: " + step.question();
                        String rawOutput = investigatorAgent.investigate(contextAwareQuestion, topResults, context.getLanguage());
                        return CitationUtil.enrichCiteTags(rawOutput, context.getPaperDatabase()); 
                    }
                    return (String) null;
                } finally {
                    MDC.remove("jobId"); 
                }
            }, ioExecutor)
        ).toList();

        // Wait for all results and filter out nulls
        return futures.stream()
                .map(CompletableFuture::join)
                .filter(Objects::nonNull)
                .collect(Collectors.toList());
    }

    public List<String> executeAdversarialSearch(ResearchContext context, List<PlanStep> steps, String draftContext) {
        List<CompletableFuture<String>> futures = steps.stream().map((PlanStep step) -> 
            CompletableFuture.supplyAsync(() -> {
                MDC.put("jobId", context.getJobId());
                try {
                    sseService.sendUpdate(context.getJobId(), "Challenging claims: " + step.question());
                    
                    // For counter-research, a smaller pool (50) and higher threshold (40) is sufficient
                    List<ValidatedResult> topResults = fetchAndValidate(context, step, 50, 40);
                    
                    if (!topResults.isEmpty()) {
                        String rawOutput = adversarialAgent.investigateCounterClaims(draftContext, step.question(), topResults, context.getLanguage());
                        return CitationUtil.enrichCiteTags(rawOutput, context.getPaperDatabase());
                    }
                    return (String) null;
                } finally {
                    MDC.remove("jobId"); 
                }
            }, ioExecutor)
        ).toList();

        return futures.stream()
                .map(CompletableFuture::join)
                .filter(Objects::nonNull)
                .collect(Collectors.toList());
    }

    private List<ValidatedResult> fetchAndValidate(ResearchContext context, PlanStep step, int limit, int minScore) {
        List<DetailedResult> rawApiResults = apiClient.search(step.vectorQuery());
        if (rawApiResults == null || rawApiResults.isEmpty()) return List.of();

        List<DetailedResult> uniqueApiResults = rawApiResults.stream()
            .collect(Collectors.toMap(
                r -> r.title().toLowerCase().trim(),
                r -> new DetailedResult(r.id(), r.title(), r.summary(), r.score(), r.contentUrl()),
                (existing, replacement) -> existing
            )).values().stream().toList();

        // Run OpenAlex validation requests in parallel within this task
        List<ValidatedResult> validatedResults = uniqueApiResults.parallelStream()
                .limit(limit)
                .map(validationService::validatePaper)
                .filter(v -> !v.isRetracted())
                // Duplicate killer
                .filter(v -> {
                    String uniqueKey = (v.doi() != null && !v.doi().isBlank()) ? 
                                       v.doi() : 
                                       v.originalResult().title().toLowerCase().replaceAll("[^a-z0-9]", "");
                    return context.getGloballySeenDois().add(uniqueKey); // Returns false if already present
                })
                .peek(v -> context.getPaperDatabase().put(v.originalResult().id(), v)) // SHARED DATABASE
                .toList();

        List<RankingAgent.RankEvaluation> evals = rankingAgent.rankWithValidation(step.question(), validatedResults, context.getLanguage());
        
        return evals.stream()
                .filter(eval -> eval.score() >= minScore)
                .map(eval -> validatedResults.stream().filter(v -> v.originalResult().id().equals(eval.id())).findFirst().orElse(null))
                .filter(Objects::nonNull)
                .filter(v -> context.getUsedPaperIds().add(v.originalResult().id())) 
                .collect(Collectors.toList());
    }
}